name : CI/CD

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: authz-rest
      REGISTRY: ghcr.io
      REPOSITORY: ${{ github.repository }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up and Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Install Dependencies
      run: go mod tidy

    - name: Run Tests
      run: go test ./...

    - name: Build & Push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: ./main
        file: ./main/Dockerfile
        push: true
        tags: ghcr.io/${{ github.actor }}/authz-rest:latest
        build-args: |
          JWKS_URL=http://localhost:8081/realms/demo/protocol/openid-connect/certs
        
      
