name : CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: authz-rest
      REGISTRY: ghcr.io
      REPOSITORY: ${{ github.repository }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up and Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Install Dependencies
      run: go mod tidy

    - name: Run Tests
      run: go test ./...

    - name: Log in to Github Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUH_TOKEN }}

    - name: Build Docker Image
      run: |
        docker build \
          --build-arg JWKS_URL="https://keycloak.example.com/realms/demo/protocol/openid-connect/certs" \
          -t ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest .

    - name: Push Docker Image
      run: |
        docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
        
      
